- name: download filebeat
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb
    dest: /home/vagrant

- name: install filebeat
  apt:
    deb: filebeat-7.6.1-amd64.deb

- name: copy the filebeat config 
  template:
    src: filebeat.j2
    dest: /etc/filebeat/filebeat.yml

- name: start filebeat
  service:
    name: filebeat
    state: started
