- name: install filebeat
  apt:
   name: filebeat
   update_cache: yes

- name: copy the filebeat config 
  template:
    src: filebeat.j2
    dest: /etc/filebeat/filbeat.yml

- name: start filebeat
  service:
   name: filebeat
   state: started
