- name: Install nginx
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - nginx
    - apache2-utils              

- name: copy nginx config file
  template:
    src: sites-available.j2
    dest: /etc/nginx/sites-available/default

- name: start nginx
  service: 
    name: nginx
    state: started
        
