- hosts: group3
  user: vagrant
  become: yes
  tasks: 
  - name: create directory
    file:
      path: /usr/lib/jvm/open-jdk-8
      state: directory

  - name: download java tar file
    get_url:
      url: https://mirrors.huaweicloud.com/java/jdk/8u151-b12/jdk-8u151-linux-i586.tar.gz
      dest: /usr/lib/jvm/open-jdk-8
      owner: vagrant
      mode: "0644"
  
  - name: Extract the tar file to /usr/lib/jvm/open-jdk-8
    unarchive: 
      src: /usr/lib/jvm/open-jdk-8
      dest: /usr/lib/jvm/open-jdk-8

  - name: Update Alternatives
    shell: 'for f in `ls /usr/lib/jvm/open-jdk-8/jdk1.8.0_151/bin`; do update-alternatives --install "/usr/bin/${f}" "/usr/lib/jvm/open-jdk-8/jdk1.8.0_151/bin/${f}" 0; done'

  - name: source bashrc
    sudo: no
    shell: ~/.bashrc && export PATH=$PATH:$JAVA_HOME/bin JAVA_HOME=/usr/lib/jvm/open-jdk-8/jdk1.8.0_151/bin/ JRE_HOME=/usr/lib/jvm/open-jdk-8/jdk1.8.0_151/jre JAVA_OPT='-Djava.awt.headless=true'

  - name: source /etc/envirnonment
    sudo: no
    shell: export PATH=$PATH:$JAVA_HOME/bin export JAVA_HOME=/usr/lib/jvm/open-jdk-8/jdk1.8.0_151 export JRE_HOME=/usr/lib/jvm/open-jdk-8/jdk1.8.0_151/jre

  - name: enable multiarch
    command: dpkg --add-architecture

  - name: install deps
    apt: name={{ item }} update_cache=yes cache_valid=3600
    with_items:
     - "libc6:i386"
     - "libncurse5:i386"
     - "libstdc++6:i386"

  - name: install logstash
    sudo: yes 
    apt: https://artifacts.elastic.co/downloads/logstash/logstash-7.6.1.deb
    dest: /home/vagrant/

    
