- hosts: webservers
  user: vagrant
  become: yes
  roles:
  - { role: javalogstash }
  - { role: filebeat }
  - { role: redis }
  - { role: elasticsearch }
  - { role: nginx }
  - { role: kibana }

    
