- name: Install Kibana
  apt:
    deb: https://artifacts.elastic.co/downloads/kibana/kibana-7.0.1-amd64.deb
  sudo: yes
  dest: /home/vagrant


- name: copy the kibana config
  template:
    src: kibana.j2
    dest: /etc/kibana/kibana.yml
  sudo: yes 

  
- name: Ensure kibana is started
  service:
    name: kibana
    state: started
