- name: enable multiarch
  command: dpkg --add-architecture i386

- name: install deps
  apt: name=libc6-i386 update_cache=yes

- name: create directory
  command: mkdir -p /usr/lib/jvm/open-jdk-8
  
- name: download java
  get_url:
    url: https://mirrors.huaweicloud.com/java/jdk/8u151-b12/jdk-8u151-linux-i586.tar.gz
    dest: /usr/lib/jvm/open-jdk-8/
    mode: '0440'
    validate_certs: no

- name: unpack archive
  unarchive:
    src: /usr/lib/jvm/open-jdk-8/jdk-8u151-linux-i586.tar.gz
    dest: /usr/lib/jvm/open-jdk-8/
    remote_src: yes

- name: fix ownership
  file: state=directory path=/usr/lib/jvm/open-jdk-8 owner=vagrant group=vagrant recurse=yes

- name: update alternatives for java
  alternatives:
    name: java
    path: /usr/lib/jvm/open-jdk-8/jdk1.8.0_151/bin/java
    link: /usr/bin/java
    priority: 2000 

- name: Update the bashrc config file
  blockinfile:
    path: /home/vagrant/.bashrc
    block: | 
      export PATH=$PATH:$JAVA_HOME/bin
      export JAVA_HOME=/usr/lib/jvm/open-jdk-8/jdk1.8.0_151/bin/
      export JRE_HOME=/usr/lib/jvm/open-jdk-8/jdk1.8.0_151/jre
      export JAVA_OPT='-Djava.awt.headless=true'

- name: Update the environment file
  blockinfile:
    path: /etc/environment
    block: | 
      export PATH=$PATH:$JAVA_HOME/bin
      export JAVA_HOME=/usr/lib/jvm/open-jdk-8/jdk1.8.0_151
      export JRE_HOME=/usr/lib/jvm/open-jdk-8/jdk1.8.0_151/jre

 
 

