
- name: create directory
  command: mkdir -p /usr/lib/jvm/open-jdk-8
  
- name: download java
  get_url:
    url: https://mirrors.huaweicloud.com/java/jdk/8u151-b12/jdk-8u151-linux-i586.tar.gz
    dest: /usr/lib/jvm/open-jdk-8


- name: unpack archive
  action: shell tar -xvzf /usr/lib/jvm/open-jdk-8/jdk-8u151-linux-i586.tar.gz /usr/lib/jvm/open-jdk-8/

- name: fix ownership
  file: state=directory path=/usr/lib/jvm/open-jdk-8 owner=vagrant group=vagrant recurse=yes

- make java available for system by updating alternatives
  command: sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/open-jdk-8/bin/java 2
  command: sudo update-alternatives --install /usr/bin/jar jar /usr/lib/jvm/open-jdk-8/bin/jar 2
  command: sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/open-jdk-8/bin/javac 2
  command: sudo update-alternatives --set jar /usr/lib/jvm/open-jdk-8/bin/jar
  command: sudo update-alternatives --set javac /usr/lib/jvm/open-jdk-8/bin/javac

# check remote file
- stat: path= ~/.bashrc
  register: file_path

- copy:
    content: |
              export PATH=$PATH:$JAVA_HOME/bin
              export JAVA_HOME=/usr/lib/jvm/open-jdk-8/jdk1.8.0_151/bin/
              export JRE_HOME=/usr/lib/jvm/open-jdk-8/jdk1.8.0_151/jre
              export JAVA_OPT='-Djava.awt.headless=true'
    dest: ~/.bashrc

- copy:
    content: |
              export PATH=$PATH:$JAVA_HOME/bin
              export JAVA_HOME=/usr/lib/jvm/open-jdk-8/jdk1.8.0_151
              export JRE_HOME=/usr/lib/jvm/open-jdk-8/jdk1.8.0_151/jre
    dest: /etc/environment
 
- name: enable multiarch
  command: dpkg --add-architecture

- name: install deps
  apt: name= libc6-i386 update_cache=yes cache_valid=3600
 

