- name: download the elasticsearch deb file
  command: wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.1-amd64.deb

- name: Install Elasticsearch
  apt:
    deb: elasticsearch-7.6.1-amd64.deb

- name: configure template
  template: 
    src: config.j2
    dest: /etc/elasticsearch/elasticsearch.yml

- name: start elasticsearch 
  service:
    name: elasticsearch
    state: started
