- name: install java
  apt:
    name: default-jre
  update_cache: yes

- name: download the elasticsearch deb file
  apt:
    deb: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.0.1-amd64.deb
  dest: /home/vagrant
  sudo: yes

- name: config template
  template: 
    src: config.j2
    dest: /etc/elasticsearch/elasticsearch.yml

- name: start elasticsearch 
  service:
    name: elasticsearch
    state: started
